### ISSUE TITLE
Unable to compile if pytorch version is >1.4?

### ISSUE THREAD

**Issue by lohzhunyewcs** [ying09/TextFuseNet#12]
Hi,

I'm trying to pair the detection model with a recognition model that I have already trained while working on the character annotations. However, since I've trained the model in 1.6 and pytorch doesn't have forward compatibility in a certain case, I need to use pytorch 1.6 to compile the detectron for textfusenet. There seems to be an issue with older versions of detectron when trying to compile using pytorch >1.4.

I've tried compiling the new detectron on my own and using the fvcore that was provided but I was only met with the error AttributionError: module 'fvcore' has no attribute '__version__'

I've also tried using pip's fvcore but it just came out with another error about missing texfusenet key which I assume means the detectron2 provided is modified.

Is there anyway to use textfusenet with a newer version of pytorch?

**Comment by Real-YeJ** [comment]
@lohzhunyewcs    This implementation is based on early detectron2.  I'm not sure how the version update of detectron2 will affect TextFuseNet. For fvcore, I modified a part of code for training more conveniently, and you can check it in fvcore-master.zip.  if a newer version of pytorch dose not work, maybe you can merge the  code of TextFuseNet to a new detecton2, which is achievable.

**Comment by lohzhunyewcs** [comment]
@Real-YeJ I see, was any part of the detectron2 code changed besides fvcore?(since detectron2 uses fvcore)

**Comment by Real-YeJ** [comment]
@lohzhunyewcs In **checkpoint.py** of fvcore-master.zip. I've made notes.

**Comment by lohzhunyewcs** [comment]
@Real-YeJ In that file it only seems to be 2 changes to checkpoint.py of fvcore, does this mean there's no detectron2 code change at all and I would only have to change those 2 things in the latest version of fvcore?

**Comment by Real-YeJ** [comment]
@lohzhunyewcs 
sorry, I forgot which file of detectron2 to add an bool value to the load function of checkpoint after modified the fvcore.  If I remember correctly, this problem is easy to find in the log and modify.

**Comment by lohzhunyewcs** [comment]
@Real-YeJ 
I see okay thanks! I'll give it a try then

**Comment by jiyeon2781** [comment]
Did you successfully compile through pytorch 1.6?

**Comment by lohzhunyewcs** [comment]
@jiyeon2781 
I forked detectron2 and made it work. It should support up to pytorch 1.7
https://github.com/lohzhunyewcs/detectron2

**Comment by jiyeon2781** [comment]
Thank you! :)
